export { default as SignInPage } from './SignIn'
export { default as SignUpPage } from './SignUp'
export { default as VerificationPage } from './Verification'
export { default as ResetPasswordPage } from './ResetPassword'
export { default as ForgotPasswordPage } from './ForgotPassword'